framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  router:
    utf8: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
