version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - web

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8000:80"   # http://localhost:8000
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web

networks:
  web:
    driver: bridge
